Repository rancher/cluster-api-provider-rke2, pull requests merged in 2022-11, with the labels that each got.

#13 Tilt changes
  .gitignore
  LICENSE
  README.md
  bootstrap/config/manager/manager.yaml
  controlplane/config/manager/manager.yaml
Labels: kind/bug

#16 Fix CRD paths in envtest setup
  .github/workflows/ci.yml
  bootstrap/internal/controllers/suite_test.go
  controlplane/internal/controllers/suite_test.go
Labels: kind/bug

#18 Adding first structs for the API
  bootstrap/api/v1alpha1/rke2config_types.go
  bootstrap/api/v1alpha1/rke2config_webhook.go
  bootstrap/api/v1alpha1/rke2configtemplate_types.go
  bootstrap/api/v1alpha1/rke2configtemplate_webhook.go
  bootstrap/api/v1alpha1/webhook_suite_test.go
  bootstrap/api/v1alpha1/zz_generated.deepcopy.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/main.go
  controlplane/api/v1alpha1/rke2controlplane_types.go
  controlplane/api/v1alpha1/rke2controlplane_webhook.go
  controlplane/api/v1alpha1/rke2controlplanetemplate_types.go
  controlplane/api/v1alpha1/rke2controlplanetemplate_webhook.go
  controlplane/api/v1alpha1/webhook_suite_test.go
  controlplane/api/v1alpha1/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/main.go
  docs/RKE2 Cluster API Provider - Data Type definitions.md
  docs/Structures Relationships.uml
  go.mod
  go.sum
Labels: kind/feature

#27 Improve main.go after scaffolding
  bootstrap/api/v1alpha1/rke2config_types.go
  bootstrap/api/v1alpha1/rke2configtemplate_types.go
  bootstrap/api/v1alpha1/webhook_suite_test.go
  bootstrap/main.go
  controlplane/main.go
  go.mod
Labels: kind/feature

#33 First Draft implementations of Bootstrap provider and ControlPlane provider
  bootstrap/api/v1alpha1/condition_consts.go
  bootstrap/api/v1alpha1/rke2config_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/main.go
  controlplane/api/v1alpha1/condition_consts.go
  controlplane/api/v1alpha1/rke2controlplane_types.go
  controlplane/api/v1alpha1/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/rbac/role.yaml
  controlplane/internal/controllers/const.go
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/internal/controllers/scale.go
  controlplane/main.go
  go.mod
  go.sum
  pkg/machinefilters/machine_filters.go
  pkg/rke2/config.go
  pkg/rke2/control_plane.go
  pkg/rke2/failure_domain.go
  pkg/rke2/machine_collection.go
  pkg/rke2/management_cluster.go
  pkg/rke2/workload_cluster.go
  pkg/util/util.go
  samples/docker/rke2-sample.yaml
Labels: kind/feature

#37 Fix repo link in readme
  README.md
Labels: kind/documentation

#38 Fix license year and add where its missing
  bootstrap/api/v1alpha1/condition_consts.go
  controlplane/api/v1alpha1/condition_consts.go
  controlplane/internal/controllers/const.go
  controlplane/internal/controllers/scale.go
  pkg/machinefilters/machine_filters.go
  pkg/rke2/config.go
  pkg/rke2/control_plane.go
  pkg/rke2/failure_domain.go
  pkg/rke2/machine_collection.go
  pkg/rke2/management_cluster.go
  pkg/rke2/workload_cluster.go
  pkg/util/util.go
  version/version.go
Labels: kind/refactor
