Repository rancher/cluster-api-provider-rke2, pull requests merged in 2023-05, with the labels that each got.

#130 Fix for disablePlugin field not validated correctly
  controlplane/api/v1alpha1/rke2controlplane_types.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/manager/manager.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  samples/aws/external/cluster-template-external-cloud-provider.yaml
  samples/docker/disable-components/rke2-sample.yaml
Labels: kind/bug, size/xs

#131 controlplane/locking: increase test coverage
  pkg/locking/control_plane_init_mutex_test.go
Labels: kind/cleanup

#124 Support ignition format for generating user data
  .golangci.yml
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/internal/ignition/clc/clc.go
  bootstrap/internal/ignition/clc/clc_test.go
  bootstrap/internal/ignition/ignition.go
  bootstrap/internal/ignition/ignition_test.go
  go.mod
  samples/aws/README.md
  samples/aws/ignition-external/cluster-template-aws-ignition-external-cloud-provider.yaml
Labels: kind/feature

#135 Dependabot/go modules/GitHub.com/onsi/ginkgo/v2 2.9.4
  bootstrap/api/v1alpha1/webhook_suite_test.go
  bootstrap/internal/cloudinit/cloudinit_suite_test.go
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/internal/controllers/suite_test.go
  controlplane/api/v1alpha1/webhook_suite_test.go
  controlplane/internal/controllers/suite_test.go
  go.mod
  go.sum
  pkg/kubeconfig/kubeconfig.go
  pkg/locking/control_plane_init_mutex.go
  pkg/rke2/control_plane.go
  pkg/rke2/management_cluster.go
  pkg/rke2/suite_test.go
  pkg/secret/certificates.go
  pkg/util/suite_test.go
Labels: area/dependency, kind/feature
