Repository rancher/cluster-api-provider-rke2, pull requests merged in 2023-11, with the labels that each got.

#195 Run ignition bootstrap script only once
  bootstrap/internal/ignition/butane/butane.go
  bootstrap/internal/ignition/butane/butane_test.go
Labels: kind/bug

#189 Fix nil machine occurence during upgrade
  controlplane/internal/controllers/rke2controlplane_controller_test.go
  controlplane/internal/controllers/suite_test.go
  pkg/rke2/workload_cluster.go
Labels: kind/bug

#190 Add arbitrary data field
  bootstrap/api/v1alpha1/rke2config_types.go
  bootstrap/api/v1alpha1/zz_generated.deepcopy.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/internal/cloudinit/cloudinit.go
  bootstrap/internal/cloudinit/cloudinit_test.go
  bootstrap/internal/cloudinit/controlplane_init.go
  bootstrap/internal/cloudinit/controlplane_join.go
  bootstrap/internal/cloudinit/worker_join.go
  bootstrap/internal/controllers/rke2config_controller.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  pkg/rke2/workload_cluster_test.go
Labels: kind/feature

#199 Re-enable ability to choose to disable cloud controller
  pkg/rke2/config.go
Labels: kind/feature

#188 Add maxsurge option for control plane upgrade
  controlplane/api/v1alpha1/rke2controlplane_types.go
  controlplane/api/v1alpha1/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure/cluster-template-docker.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2e/helpers.go
Labels: kind/feature

#201 chore: update metadata for v0.2 release
  metadata.yaml
Labels: area/build-and-release, kind/feature

#203 fix: bump versions and change template for e2e
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure/cluster-template-docker.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: area/testing, kind/bug

#204 test: add disk space cleanup
  .github/workflows/e2e.yml
Labels: area/testing, kind/bug

#205 Fix selinux in ignition for SLE micro
  bootstrap/internal/ignition/ignition.go
  bootstrap/internal/ignition/ignition_test.go
Labels: kind/feature

#206 [release-0.2] Fix selinux in ignition for SLE micro
  bootstrap/internal/ignition/ignition.go
  bootstrap/internal/ignition/ignition_test.go
Labels: kind/bug

#209 Create bootstrap-success before setting selinux to enforcing mode
  bootstrap/internal/ignition/butane/butane.go
  bootstrap/internal/ignition/ignition.go
  bootstrap/internal/ignition/ignition_test.go
Labels: kind/bug

#211 [release-0.2] Create bootstrap-success before setting selinux to enforcing mode
  bootstrap/internal/ignition/butane/butane.go
  bootstrap/internal/ignition/ignition.go
  bootstrap/internal/ignition/ignition_test.go
Labels: kind/bug
