Repository rancher/cluster-api-provider-rke2, pull requests merged in 2023-02, with the labels that each got.

#72 Impl-register-server
  .gitignore
  bootstrap/api/v1alpha1/rke2config_types.go
  bootstrap/api/v1alpha1/zz_generated.deepcopy.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/internal/cloudinit/cloudinit.go
  bootstrap/internal/cloudinit/cloudinit_suite_test.go
  bootstrap/internal/cloudinit/cloudinit_test.go
  bootstrap/internal/cloudinit/controlplane_init.go
  bootstrap/internal/cloudinit/controlplane_join.go
  bootstrap/internal/cloudinit/worker_join.go
  bootstrap/internal/controllers/rke2config_controller.go
  controlplane/api/v1alpha1/rke2controlplane_types.go
  controlplane/api/v1alpha1/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/internal/controllers/scale.go
  go.mod
  go.sum
  pkg/rke2/config.go
  pkg/rke2/config_test.go
  pkg/rke2/control_plane.go
  pkg/rke2/machine_filters.go
  pkg/rke2/machine_filters_test.go
  pkg/rke2/management_cluster.go
  pkg/rke2/registries.go
  pkg/rke2/registries_test.go
  pkg/rke2/registries_types.go
  pkg/util/suite_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  samples/aws/external/cluster-template-external-cloud-provider.yaml
  samples/aws/internal/cluster-template.yaml
  samples/aws/rke2-sample.yaml
  samples/docker/air-gapped/rke2-sample.yaml
  samples/docker/air-gapped/test.env
  samples/docker/air-gapped/test2.env
  samples/docker/online-default/rke2-sample.yaml
  samples/docker/priv-registries/rke2-sample.yaml
  samples/docker/test.env
Labels: kind/feature, size/m

#83 fix: spelling mistake for target
  Makefile
Labels: kind/bug

#85 Github action for releasing new versions
  .github/workflows/release.yml
  Makefile
  bootstrap/internal/controllers/rke2config_controller.go
  pkg/rke2/registries_test.go
  pkg/util/util.go
Labels: kind/feature

#86 Fix typo in Makefile for Bootstrap provider
  Makefile
  samples/aws/external/cluster-template-external-cloud-provider.yaml
Labels: kind/bug
