Repository rancher/cluster-api-provider-rke2, pull requests merged in 2023-03, with the labels that each got.

#52 Add .golangci.yml config & golangci-lint.yml github action
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
Labels: kind/feature

#89 Updated VMware example files due to updates to the RKE2 Provider
  samples/vmware/README.md
  samples/vmware/cluster.yaml
  samples/vmware/machinedeployment.yaml
  samples/vmware/namespace.yaml
  samples/vmware/rke2configtemplate.yaml
  samples/vmware/rke2controlplane.yaml
  samples/vmware/vmware-cpi-with-csi.yaml
  samples/vmware/vspherecluster.yaml
  samples/vmware/vspheremachinetemplate.yaml
Labels: kind/bug

#90 Adding a Getting Started section to the README
  README.md
Labels: kind/documentation

#99 Add metal3 example
  samples/metal3/sample-cluster.yaml
Labels: kind/feature, size/s

#93 docs: added link to slack
  README.md
Labels: kind/documentation, size/xs

#102 Added an AWS README guide
  samples/aws/README.md
  samples/aws/rke2-sample.yaml
Labels: kind/documentation, size/xs

#107 fixed linting issues (first pass)
  .github/workflows/golangci-lint.yml
  .golangci.yml
  bootstrap/api/v1alpha1/condition_consts.go
  bootstrap/api/v1alpha1/groupversion_info.go
  bootstrap/api/v1alpha1/rke2config_types.go
  bootstrap/api/v1alpha1/rke2config_webhook.go
  bootstrap/api/v1alpha1/rke2configtemplate_types.go
  bootstrap/api/v1alpha1/rke2configtemplate_webhook.go
  bootstrap/api/v1alpha1/webhook_suite_test.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/internal/cloudinit/cloudinit.go
  bootstrap/internal/cloudinit/cloudinit_suite_test.go
  bootstrap/internal/cloudinit/controlplane_init.go
  bootstrap/internal/cloudinit/controlplane_join.go
  bootstrap/internal/cloudinit/worker_join.go
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/internal/controllers/suite_test.go
  bootstrap/main.go
  controlplane/api/v1alpha1/condition_consts.go
  controlplane/api/v1alpha1/groupversion_info.go
  controlplane/api/v1alpha1/rke2controlplane_types.go
  controlplane/api/v1alpha1/rke2controlplane_webhook.go
  controlplane/api/v1alpha1/rke2controlplanetemplate_types.go
  controlplane/api/v1alpha1/rke2controlplanetemplate_webhook.go
  controlplane/api/v1alpha1/webhook_suite_test.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  controlplane/internal/controllers/const.go
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/internal/controllers/scale.go
  controlplane/internal/controllers/suite_test.go
  controlplane/main.go
  pkg/consts/global_consts.go
  pkg/kubeconfig/kubeconfig.go
  pkg/locking/control_plane_init_mutex.go
  pkg/locking/control_plane_init_mutex_test.go
  pkg/rke2/config.go
  pkg/rke2/config_test.go
  pkg/rke2/control_plane.go
  pkg/rke2/machine_filters.go
  pkg/rke2/machine_filters_test.go
  pkg/rke2/management_cluster.go
  pkg/rke2/registries.go
  pkg/rke2/registries_test.go
  pkg/rke2/registries_types.go
  pkg/rke2/suite_test.go
  pkg/rke2/workload_cluster.go
  pkg/secret/certificates.go
  pkg/util/suite_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  version/version.go
Labels: kind/cleanup, size/m

#95 Add json tags to registry types
  pkg/rke2/registries_types.go
Labels: kind/bug

#110 Fixed #28 CIS Profile now works and is different for v1.25+ and v1.24-
  bootstrap/api/v1alpha1/rke2config_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/internal/cloudinit/cloudinit.go
  bootstrap/internal/cloudinit/cloudinit_test.go
  bootstrap/internal/cloudinit/controlplane_init.go
  bootstrap/internal/cloudinit/worker_join.go
  bootstrap/internal/controllers/rke2config_controller.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  pkg/consts/global_consts.go
  pkg/rke2/config.go
  pkg/rke2/config_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  samples/docker/cis-profile/rke2-sample.yaml
Labels: kind/feature

#116 Fixed a mistake in the description of ExtraArgs field
  bootstrap/api/v1alpha1/rke2config_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
Labels: kind/bug, size/xs

#115 moved useful constants to own package
  bootstrap/internal/controllers/rke2config_controller.go
  pkg/consts/global_consts.go
  pkg/rke2/config.go
  pkg/rke2/config_test.go
  pkg/secret/certificates.go
Labels: kind/refactor, size/xs

#108 Air Gapped installation procedure docs and example for CAPD
  docs/AIR-GAPPED-INSTALL.md
  docs/old/RKE2 Cluster API Provider - Data Type definitions.md
  docs/old/Structures Relationships.uml
  samples/docker/air-gapped/image-building/Dockerfile
  samples/docker/air-gapped/image-building/README.md
  samples/docker/air-gapped/image-building/artifact-list.txt
  samples/docker/air-gapped/image-building/download-rke2-artifacts.sh
  samples/docker/air-gapped/image-building/files/install.sh
Labels: kind/documentation, size/s, air-gapped

#114 implemented additionCloudInit configuration in the API
  Makefile
  bootstrap/api/v1alpha1/rke2config_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/internal/cloudinit/cloudinit.go
  bootstrap/internal/cloudinit/cloudinit_test.go
  bootstrap/internal/cloudinit/controlplane_init.go
  bootstrap/internal/cloudinit/controlplane_join.go
  bootstrap/internal/cloudinit/worker_join.go
  bootstrap/internal/controllers/rke2config_controller.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  go.mod
Labels: kind/feature, size/s

#121 chore: change event trigger
  .github/workflows/e2e.yml
Labels: kind/cleanup

#122 chore: change to use explicit kustomize path
  .github/workflows/e2e.yml
  Makefile
Labels: kind/cleanup

#123 Validate/default control plane object with webhooks
  bootstrap/api/v1alpha1/rke2config_webhook.go
  controlplane/api/v1alpha1/rke2controlplane_webhook.go
Labels: kind/bug
