Repository rancher/cluster-api-provider-rke2, pull requests merged in 2024-05, with the labels that each got.

#302 Check rke2-serving secret to determine controlPlane.Status.Initialized
  controlplane/internal/controllers/rke2controlplane_controller.go
  pkg/rke2/workload_cluster.go
  pkg/rke2/workload_cluster_test.go
Labels: kind/bug

#313 🐛 Add old AgentConfig version conversion in favor of a new field
  bootstrap/api/v1alpha1/conversion.go
  bootstrap/api/v1alpha1/conversion_test.go
  bootstrap/api/v1alpha1/zz_generated.conversion.go
  bootstrap/api/v1beta1/rke2config_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/internal/controllers/rke2config_controller.go
  controlplane/api/v1alpha1/conversion.go
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  go.mod
  pkg/rke2/machine_filters_test.go
  samples/aws/external/cluster-template-external-cloud-provider.yaml
  samples/aws/ignition-external/cluster-template-aws-ignition-external-cloud-provider.yaml
  samples/aws/internal/cluster-template.yaml
  samples/docker/air-gapped/rke2-sample.yaml
  samples/docker/cis-profile/rke2-sample.yaml
  samples/docker/disable-components/rke2-sample.yaml
  samples/docker/enable-multus/rke2-sample.yaml
  samples/docker/enable-multus/rke2controlplane-test.yaml
  samples/docker/kube-vip/rke2-sample.yaml
  samples/docker/online-default/rke2-sample.yaml
  samples/docker/priv-registries/rke2-sample.yaml
  samples/metal3/sample-cluster.yaml
  samples/vmware/machinedeployment.yaml
  samples/vmware/rke2configtemplate.yaml
  samples/vmware/rke2controlplane.yaml
  test/e2e/data/infrastructure/cluster-template-docker-legacy.yaml
  test/e2e/data/infrastructure/cluster-template-docker.yaml
  test/e2e/e2e_upgrade_test.go
Labels: area/api, kind/bug

#319 Add airGappedChecksum field to check workload version before rollout
  bootstrap/api/v1alpha1/conversion.go
  bootstrap/api/v1alpha1/zz_generated.conversion.go
  bootstrap/api/v1beta1/rke2config_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/internal/cloudinit/cloudinit.go
  bootstrap/internal/cloudinit/cloudinit_test.go
  bootstrap/internal/cloudinit/controlplane_init.go
  bootstrap/internal/cloudinit/worker_join.go
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/internal/ignition/ignition.go
  bootstrap/internal/ignition/ignition_test.go
  controlplane/api/v1alpha1/conversion.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
Labels: area/api, kind/feature

#324 test: use gomega's ContainElements
  pkg/registration/registration_test.go
Labels: kind/bug

#326 Review and update incorrectly returned results
  bootstrap/internal/controllers/rke2config_controller.go
  controlplane/internal/controllers/rke2controlplane_controller.go
Labels: kind/cleanup

#325 :bug: Check MachineConfig spec for full equality with Rke2CPSpec
  bootstrap/internal/controllers/rke2config_controller.go
  pkg/rke2/machine_filters.go
  pkg/rke2/machine_filters_test.go
Labels: kind/bug

#314 Fix ingress rules in AWS example
  samples/aws/internal/cluster-template.yaml
Labels: kind/bug

#331 📖 Add ADR for using separate CP and worker versions
  docs/adr/0000-template.md
  docs/adr/0001-separate-CP-and-worker-versions.md
Labels: kind/documentation

#334 Update AWS out-of-tree examples
  samples/aws/README.md
  samples/aws/external/cluster-template-external-cloud-provider.yaml
  samples/aws/ignition-external/cluster-template-aws-ignition-external-cloud-provider.yaml
  samples/aws/internal/cluster-template.yaml
Labels: kind/documentation
