Repository rancher/cluster-api-provider-rke2, pull requests merged in 2024-02, with the labels that each got.

#264 Make etcd snapshot location configurable
  pkg/rke2/config.go
  pkg/rke2/config_test.go
Labels: kind/refactor

#260 fix: failing e2e tests
  Makefile
  metadata.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure/cluster-template-docker.yaml
  test/e2e/e2e_test.go
Labels: area/testing, kind/bug

#267 chore: added additional workflow to test self hosted e2e
  .github/workflows/e2e-test.yml
Labels: area/testing, kind/feature

#258 :bug: Ensure we always lookup machines by node name from collection
  controlplane/internal/controllers/rke2controlplane_controller_test.go
  pkg/rke2/control_plane.go
  pkg/rke2/workload_cluster.go
  pkg/rke2/workload_cluster_test.go
Labels: kind/bug

#268 [release-0.2] Fix: e2e tests
  .github/workflows/e2e.yml
  Makefile
  metadata.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure/cluster-template-docker.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/e2e_test.go
Labels: kind/bug

#261 ✨ feat: add support for cluster class
  README.md
  bootstrap/api/v1beta1/rke2config_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/config/crd/kustomization.yaml
  bootstrap/config/crd/patches/webhook_in_rke2configs.yaml
  controlplane/api/v1alpha1/conversion.go
  controlplane/api/v1alpha1/rke2controlplanetemplate_types.go
  controlplane/api/v1alpha1/zz_generated.conversion.go
  controlplane/api/v1beta1/conversion.go
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/api/v1beta1/rke2controlplanetemplate_types.go
  controlplane/api/v1beta1/rke2controlplanetemplate_webhook.go
  controlplane/api/v1beta1/rke2controlplanetemplate_webhook_test.go
  controlplane/api/v1beta1/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  controlplane/config/crd/kustomization.yaml
  controlplane/config/crd/patches/webhook_in_rke2controlplanes.yaml
  controlplane/config/crd/patches/webhook_in_rke2controlplanetemplates.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  samples/docker/clusterclass/clusterclass-quick-start.yaml
  samples/docker/clusterclass/rke2-sample.yaml
Labels: kind/feature

#273 Fetch additional files from secrets
  bootstrap/internal/controllers/rke2config_controller.go
Labels: kind/bug

#274 [release-0.2] Fetch additional files from secrets
  bootstrap/internal/controllers/rke2config_controller.go
Labels: kind/bug
