Repository rancher/cluster-api-provider-rke2, pull requests merged in 2024-03, with the labels that each got.

#278 [release-0.2] Differentiate etcd backup location based on the parameters
  pkg/rke2/config.go
  pkg/rke2/config_test.go
Labels: kind/refactor

#266 feat: added control plane endpoint registration method
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/api/v1beta1/types.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  pkg/registration/registration.go
  pkg/registration/registration_test.go
Labels: area/api, kind/feature

#286 feat: add devcontainer
  .devcontainer/devcontainer.json
  .github/dependabot.yml
Labels: kind/feature

#289 🌱 Bump CAPI to v1.7.0-beta.0
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .golangci.yml
  Makefile
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/main.go
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/internal/controllers/scale.go
  controlplane/main.go
  go.mod
  go.sum
  metadata.yaml
  pkg/rke2/control_plane.go
  pkg/rke2/workload_cluster.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
Labels: area/dependency, kind/feature
