Repository rancher/cluster-api-provider-rke2, pull requests merged in 2024-11, with the labels that each got.

#491 docs: Fix file references
  docs/book/src/01_user/01_getting-started.md
  docs/book/src/02_topics/01_air-gapped-installation.md
Labels: kind/documentation

#492 Fix 00_introduction.md bad Developer Guide link
  docs/book/src/00_introduction.md
Labels: kind/documentation

#494 ci: Check for broken links in MD files
  .github/workflows/pr-md-link-check.yml
  .markdown-link-check.json
  README.md
  docs/book/src/03_examples/01_aws.md
  docs/old/RKE2 Cluster API Provider - Data Type definitions.md
Labels: area/ci

#484 chore: Prepare main branch for v0.9 development
  docs/book/src/01_user/01_getting-started.md
  metadata.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: area/build-and-release, kind/support

#490 fix: remove deprecated grpc.WithBlock
  pkg/etcd/etcd.go
Labels: area/dependency, kind/bug

#477 Bump CAPI to v1.8.5
  Makefile
  bootstrap/config/crd/patches/webhook_in_rke2configs.yaml
  bootstrap/config/crd/patches/webhook_in_rke2configtemplates.yaml
  bootstrap/config/manager/manager.yaml
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/main.go
  controlplane/config/crd/patches/webhook_in_rke2controlplanes.yaml
  controlplane/config/crd/patches/webhook_in_rke2controlplanetemplates.yaml
  controlplane/config/manager/manager.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/main.go
  docs/book/src/01_user/01_getting-started.md
  go.mod
  go.sum
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/e2e_clusterclass_test.go
  test/e2e/helpers.go
Labels: area/dependency, kind/support

#503 Set control plane version in status
  controlplane/internal/controllers/rke2controlplane_controller.go
Labels: kind/bug

#506 Prepare main branch for v0.9 development
  docs/book/src/01_user/01_getting-started.md
  metadata.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: kind/feature
