Repository rancher/cluster-api-provider-rke2, pull requests merged in 2024-10, with the labels that each got.

#456 Add prime image builds
  .github/workflows/release.yml
Labels: kind/feature

#445 📖 Update notes on post-release activities
  docs/release.md
Labels: area/documentation

#462 Add missing token permissions for release
  .github/workflows/release.yml
Labels: kind/bug

#469 Patch legacy annotation on pre 0.3 RKE2 control planes
  controlplane/api/v1alpha1/rke2controlplane_types.go
  controlplane/internal/controllers/rke2controlplane_controller.go
Labels: kind/feature

#470 Backport: Change organisation name in Makefile
  .golangci.yml
  Dockerfile
  Makefile
  README.md
  bootstrap/PROJECT
  bootstrap/config/default/manager_image_patch.yaml
  bootstrap/internal/cloudinit/cloudinit.go
  bootstrap/internal/cloudinit/controlplane_init.go
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/internal/controllers/suite_test.go
  bootstrap/internal/ignition/butane/butane.go
  bootstrap/internal/ignition/butane/butane_test.go
  bootstrap/internal/ignition/ignition.go
  bootstrap/internal/ignition/ignition_test.go
  bootstrap/main.go
  controlplane/PROJECT
  controlplane/api/v1alpha1/rke2controlplane_types.go
  controlplane/api/v1alpha1/rke2controlplane_webhook.go
  controlplane/api/v1alpha1/zz_generated.deepcopy.go
  controlplane/config/default/manager_image_patch.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/internal/controllers/rke2controlplane_controller_test.go
  controlplane/internal/controllers/scale.go
  controlplane/internal/controllers/suite_test.go
  controlplane/main.go
  go.mod
  hack/version.sh
  pkg/kubeconfig/kubeconfig.go
  pkg/registration/registration.go
  pkg/registration/registration_test.go
  pkg/rke2/config.go
  pkg/rke2/config_test.go
  pkg/rke2/control_plane.go
  pkg/rke2/machine_filters.go
  pkg/rke2/machine_filters_test.go
  pkg/rke2/registries.go
  pkg/rke2/registries_test.go
  pkg/rke2/registries_types.go
  pkg/rke2/suite_test.go
  pkg/rke2/workload_cluster.go
  pkg/rke2/workload_cluster_test.go
  pkg/secret/certificates.go
  pkg/util/util.go
  samples/aws/README.md
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/helpers.go
  test/e2e/metadata_e2e_test.go
  tilt-provider.json
Labels: kind/cleanup

#473 Build and Push Prime images using prime registry secrets from vault
  .github/workflows/release.yml
Labels: kind/feature

#474 Add PSA file to API
  bootstrap/api/v1alpha1/conversion.go
  bootstrap/api/v1alpha1/zz_generated.conversion.go
  bootstrap/api/v1beta1/rke2config_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  controlplane/api/v1alpha1/conversion.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  pkg/rke2/config.go
Labels: kind/feature

#480 Add a CIS and PSA configuration docs
  docs/book/src/02_topics/03_cis-psa.md
  docs/book/src/SUMMARY.md
Labels: area/documentation

#479 Move provider examples to doc book
  docs/book/src/03_examples/00.md
  docs/book/src/03_examples/01_aws.md
  docs/book/src/03_examples/02_vsphere.md
  docs/book/src/03_examples/03_docker.md
  docs/book/src/04_developer/00.md
  docs/book/src/04_developer/01_development.md
  docs/book/src/04_developer/02_releasing.md
  docs/book/src/05_reference/00.md
  docs/book/src/SUMMARY.md
  examples/aws/cluster-template.yaml
  examples/aws/ignition/cluster-template-ignition.yaml
  examples/docker/air-gapped/image-building/Dockerfile
  examples/docker/air-gapped/image-building/README.md
  examples/docker/air-gapped/image-building/artifact-list.txt
  examples/docker/air-gapped/image-building/download-rke2-artifacts.sh
  examples/docker/air-gapped/image-building/files/install.sh
  examples/docker/air-gapped/rke2-sample.yaml
  examples/docker/cis-profile/rke2-sample.yaml
  examples/docker/clusterclass/clusterclass-quick-start.yaml
  examples/docker/clusterclass/rke2-sample.yaml
  examples/docker/disable-components/rke2-sample.yaml
  examples/docker/enable-multus/rke2-sample.yaml
  examples/docker/enable-multus/rke2controlplane-test.yaml
  examples/docker/kube-vip/rke2-sample.yaml
  examples/docker/online-default/cluster-template.yaml
  examples/docker/priv-registries/rke2-sample.yaml
  examples/metal3/sample-cluster.yaml
  examples/vmware/cluster-template.yaml
Labels: area/documentation

#482 Move from docker build to buildx
  .github/workflows/release.yml
  Dockerfile
  Makefile
Labels: kind/enhancement
