Repository rancher/cluster-api-provider-rke2, pull requests merged in 2024-09, with the labels that each got.

#428 docs: edit README to add link to book
  README.md
Labels: kind/documentation

#424 test: cover clusterclass in e2e tests
  .golangci.yml
  go.mod
  test/e2e/common.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/const.go
  test/e2e/data/infrastructure/cluster-from-clusterclass-template-docker.yaml
  test/e2e/data/infrastructure/clusterclass-template-docker.yaml
  test/e2e/e2e_clusterclass_test.go
  test/e2e/helpers.go
Labels: area/testing, kind/feature

#440 🐛 E2E failures in CI
  test/e2e/common.go
  test/e2e/e2e_clusterclass_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2e/e2e_upgrade_test.go
  test/e2e/helpers.go
Labels: kind/bug

#435 Implement etcd member management in pre-terminate hook
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/internal/controllers/scale.go
  pkg/rke2/control_plane.go
  test/e2e/data/infrastructure/clusterclass-template-docker.yaml
Labels: kind/bug

#436 bootstrap: switch to chrony for ignition config
  bootstrap/internal/ignition/butane/butane.go
  bootstrap/internal/ignition/butane/butane_test.go
Labels: kind/bug

#442 fix: Make GH links absolute
  docs/book/src/01_user/01_getting-started.md
Labels: kind/documentation

#433 🌱 Rename rke2ServerConfig to make it public
  pkg/rke2/config.go
Labels: kind/support

#447 🌱 Prepare main branch for v0.8 development
  metadata.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: area/build-and-release, kind/support

#448 🐛 Update getting started notes
  docs/book/src/01_user/01_getting-started.md
  samples/docker/online-default/rke2-sample.yaml
Labels: area/documentation
