Repository rancher/cluster-api-provider-rke2, pull requests merged in 2024-08, with the labels that each got.

#393 Revert back legacy e2e tests to its original state
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: kind/bug

#392 Remove actions/cache step in e2e tests GH workflow
  .github/workflows/e2e.yml
Labels: kind/flake

#395 [release-0.5] Revert back legacy e2e tests to its original state
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: kind/bug

#397 [release-0.5] Fix release workflow GH action
  .github/workflows/release.yml
Labels: kind/bug

#385 add securityContext to the manager containers
  bootstrap/config/manager/manager.yaml
  controlplane/config/manager/manager.yaml
Labels: kind/bug

#398 Drop out legacy and add default upgrade e2e tests
  .github/workflows/e2e.yml
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure/cluster-template-docker-legacy.yaml
  test/e2e/data/infrastructure/cluster-template-docker.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
  test/e2e/helpers.go
Labels: kind/refactor

#405 [release-0.5] Drop out legacy and add default upgrade e2e tests
  .github/workflows/e2e.yml
  test/e2e/config/e2e_conf.yaml
  test/e2e/data/infrastructure/cluster-template-docker-legacy.yaml
  test/e2e/data/infrastructure/cluster-template-docker.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
  test/e2e/helpers.go
Labels: kind/refactor

#368 docs: fix providers.yaml example in readme
  README.md
Labels: kind/documentation

#408 Remove time command from e2e
  Makefile
Labels: kind/feature

#409 :book: docs: Add book for CAPRKE2
  .github/workflows/docs.yml
  README.md
  docs/book/.gitignore
  docs/book/Makefile
  docs/book/README.md
  docs/book/book.toml
  docs/book/src/00_introduction.md
  docs/book/src/01_user/00.md
  docs/book/src/01_user/01_getting-started.md
  docs/book/src/02_topics/00.md
  docs/book/src/02_topics/01_air-gapped-installation.md
  docs/book/src/02_topics/02_node-registration-methods.md
  docs/book/src/03_developer/00.md
  docs/book/src/03_developer/01_development.md
  docs/book/src/03_developer/02_releasing.md
  docs/book/src/04_reference/00.md
  docs/book/src/SUMMARY.md
  docs/book/util-embed.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  scripts/install-mdbook.sh
Labels: kind/documentation

#415 chore: fix clusterclass example
  samples/docker/clusterclass/clusterclass-quick-start.yaml
  samples/docker/clusterclass/rke2-sample.yaml
Labels: kind/feature

#373 :book: docs: add pre-release actions to release guide
  docs/release.md
Labels: kind/documentation

#421 Prepare main branch for v0.7 development
  metadata.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: area/build-and-release, kind/support

#420 Clarify release cadence
  docs/release.md
Labels: area/build-and-release, kind/documentation

#422 Ignore changes injected by Turtles when doing CP rollout
  pkg/rke2/machine_filters.go
Labels: kind/bug
