Repository rancher/cluster-api-provider-rke2, pull requests merged in 2024-12, with the labels that each got.

#516 Add warning about kubevip to vSphere
  docs/book/src/03_examples/02_vsphere.md
Labels: kind/documentation

#536 docs: fix broken links
  docs/old/RKE2 Cluster API Provider - Data Type definitions.md
Labels: kind/cleanup

#537 Prepare main branch for v0.11 development
  docs/book/src/01_user/01_getting-started.md
  metadata.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: area/build-and-release, kind/support
