Repository rancher/cluster-api-provider-rke2, pull requests merged in 2024-04, with the labels that each got.

#300 Let the rke2-install.sh fail for pipe errors and undefined variables
  bootstrap/internal/ignition/butane/butane.go
Labels: kind/bug

#296 Build OpenSUSE image for CAPRKE2 in AWS
  image-builder/Makefile
  image-builder/README.md
  image-builder/aws/opensuse-1504.json
  image-builder/aws/opensuse-leap-155.json
  image-builder/aws/packer.json
  image-builder/aws/ubuntu-2204.json
  image-builder/files/features.py
  image-builder/scripts/opensuse/bootstrap.sh
  image-builder/scripts/ubuntu/bootstrap.sh
  samples/aws/README.md
  samples/aws/internal/cluster-template.yaml
Labels: kind/feature

#299 Bump CAPI to v1.7.0 minor release
  Makefile
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  go.mod
  go.sum
  test/e2e/config/e2e_conf.yaml
Labels: area/dependency, kind/feature

#306 Use spec.Version field as primarily source
  bootstrap/api/v1beta1/rke2config_types.go
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configs.yaml
  bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_rke2configtemplates.yaml
  bootstrap/internal/controllers/rke2config_controller.go
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/internal/controllers/scale.go
  pkg/rke2/config.go
  pkg/rke2/config_test.go
  pkg/rke2/control_plane.go
  pkg/rke2/machine_filters.go
  pkg/rke2/machine_filters_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  test/e2e/data/infrastructure/cluster-template-docker.yaml
  test/e2e/helpers.go
Labels: kind/bug
