Repository rancher/cluster-api-provider-rke2, pull requests merged in 2025-02, with the labels that each got.

#568 Propagate cloud provider config
  pkg/rke2/config.go
  pkg/rke2/config_test.go
Labels: kind/bug

#572 📖 Development document update and formatting
  docs/book/src/01_user/01_getting-started.md
  docs/book/src/04_developer/01_development.md
Labels: kind/documentation

#576 Provides steps to attach debugger to CAPRKE2
  docs/book/src/04_developer/01_development.md
Labels: area/documentation, kind/enhancement

#575 🐛 Filter machines being deleted from updatedReplicas count
  pkg/rke2/control_plane.go
Labels: kind/bug

#571 🌱 Bump controller-runtime to 0.20.1 and related changes
  bootstrap/api/v1beta1/rke2config_webhook.go
  bootstrap/api/v1beta1/rke2config_webhook_test.go
  bootstrap/api/v1beta1/rke2configtemplate_webhook.go
  bootstrap/api/v1beta1/webhook_suite_test.go
  bootstrap/main.go
  controlplane/api/v1beta1/rke2controlplane_webhook.go
  controlplane/api/v1beta1/rke2controlplanetemplate_webhook.go
  controlplane/api/v1beta1/rke2controlplanetemplate_webhook_test.go
  controlplane/api/v1beta1/webhook_suite_test.go
  controlplane/main.go
Labels: area/dependency

#579 chore: Prepare main branch for v0.13 development
  bootstrap/internal/ignition/butane/butane_test.go
  docs/book/src/01_user/01_getting-started.md
  metadata.yaml
  pkg/registration/registration_test.go
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: area/build-and-release

#583 Fix cloud provider installation in AWS template
  examples/aws/cluster-template.yaml
  pkg/rke2/workload_cluster_test.go
Labels: area/documentation, kind/enhancement

#584 Add embedded registry option to server config
  controlplane/api/v1alpha1/conversion.go
  controlplane/api/v1alpha1/zz_generated.conversion.go
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  docs/book/src/02_topics/04_embedded-registry.md
  docs/book/src/SUMMARY.md
  pkg/rke2/config.go
  pkg/rke2/config_test.go
Labels: kind/feature
