Repository rancher/cluster-api-provider-rke2, pull requests merged in 2025-01, with the labels that each got.

#547 Bump envtest to 1.32
  Makefile
  controlplane/internal/controllers/rke2controlplane_controller_test.go
Labels: area/dependency

#548 Bump kustomize to v5
  Makefile
  bootstrap/config/certmanager/certificate.yaml
  bootstrap/config/certmanager/kustomizeconfig.yaml
  bootstrap/config/crd/kustomization.yaml
  bootstrap/config/crd/kustomizeconfig.yaml
  bootstrap/config/crd/patches/cainjection_in_rke2configs.yaml
  bootstrap/config/crd/patches/cainjection_in_rke2configtemplates.yaml
  bootstrap/config/crd/patches/webhook_in_rke2configs.yaml
  bootstrap/config/default/kustomization.yaml
  bootstrap/config/default/kustomizeconfig.yaml
  bootstrap/config/default/manager_webhook_patch.yaml
  bootstrap/config/default/webhookcainjection_patch.yaml
  bootstrap/config/webhook/kustomizeconfig.yaml
  controlplane/config/certmanager/certificate.yaml
  controlplane/config/certmanager/kustomizeconfig.yaml
  controlplane/config/crd/kustomization.yaml
  controlplane/config/crd/kustomizeconfig.yaml
  controlplane/config/crd/patches/cainjection_in_rke2controlplanes.yaml
  controlplane/config/crd/patches/cainjection_in_rke2controlplanetemplates.yaml
  controlplane/config/default/kustomization.yaml
  controlplane/config/default/kustomizeconfig.yaml
  controlplane/config/default/manager_webhook_patch.yaml
  controlplane/config/default/webhookcainjection_patch.yaml
  controlplane/config/webhook/kustomizeconfig.yaml
Labels: kind/feature

#545 Standartize env variable in all documentation
  docs/book/src/01_user/01_getting-started.md
  docs/book/src/02_topics/01_air-gapped-installation.md
  examples/docker/air-gapped/image-building/README.md
  examples/docker/air-gapped/rke2-sample.yaml
  examples/docker/cis-profile/rke2-sample.yaml
  examples/docker/clusterclass/rke2-sample.yaml
  examples/docker/disable-components/rke2-sample.yaml
  examples/docker/enable-multus/rke2-sample.yaml
  examples/docker/kube-vip/rke2-sample.yaml
  examples/docker/priv-registries/rke2-sample.yaml
  test/e2e/data/infrastructure/cluster-from-clusterclass-template-docker.yaml
  test/e2e/e2e_clusterclass_test.go
Labels: kind/documentation

#521 Rotate kubeconfig before it expires
  controlplane/internal/controllers/rke2controlplane_controller.go
Labels: kind/feature

#552 feat: make aws credentials optional when s3 backup
  controlplane/api/v1alpha1/rke2controlplane_types.go
  controlplane/api/v1alpha1/zz_generated.conversion.go
  controlplane/api/v1alpha1/zz_generated.deepcopy.go
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/api/v1beta1/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  pkg/rke2/config.go
  pkg/rke2/config_test.go
Labels: kind/feature

#549 🐛 Fix setting folder S3 on etcd backups
  pkg/rke2/config.go
  pkg/rke2/config_test.go
Labels: kind/bug

#560 docs: Use correct env var
  docs/book/src/01_user/01_getting-started.md
Labels: kind/documentation

#563 chore: prepare main branch for v0.12 development
  docs/book/src/01_user/01_getting-started.md
  metadata.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: area/build-and-release, kind/cleanup

#564 feat: add dockerfile cross-compilation for multi-platform images
  Dockerfile
Labels: area/build-and-release, kind/feature
