Repository rancher/cluster-api-provider-rke2, pull requests merged in 2025-03, with the labels that each got.

#593 Clarify RKE2 CP Ready field meaning in status
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
Labels: area/api

#594 Use merge queue to reduce rebase effort
  .github/workflows/ci.yml
  .github/workflows/e2e.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/lint.yml
Labels: kind/enhancement

#586 Reorganize examples folder
  docs/book/src/01_user/01_getting-started.md
  docs/book/src/02_topics/01_air-gapped-installation.md
  docs/book/src/03_examples/01_aws.md
  docs/book/src/03_examples/02_vsphere.md
  docs/book/src/03_examples/03_docker.md
  examples/clusterclass/docker/cluster-template-topology.yaml
  examples/clusterclass/docker/clusterclass-template.yaml
  examples/templates/aws/cluster-template-ignition.yaml
  examples/templates/aws/cluster-template.yaml
  examples/templates/docker/air-gapped/cluster-template.yaml
  examples/templates/docker/air-gapped/image-building/Dockerfile
  examples/templates/docker/air-gapped/image-building/README.md
  examples/templates/docker/air-gapped/image-building/artifact-list.txt
  examples/templates/docker/air-gapped/image-building/download-rke2-artifacts.sh
  examples/templates/docker/air-gapped/image-building/files/install.sh
  examples/templates/docker/cluster-template-cis-profile.yaml
  examples/templates/docker/cluster-template-disable-components.yaml
  examples/templates/docker/cluster-template-kube-vip.yaml
  examples/templates/docker/cluster-template-multus-cni.yaml
  examples/templates/docker/cluster-template-private-registries.yaml
  examples/templates/docker/cluster-template.yaml
  examples/templates/docker/enable-multus/rke2controlplane-test.yaml
  examples/templates/metal3/cluster-template.yaml
  examples/templates/vmware/cluster-template.yaml
Labels: kind/cleanup

#592 Add additional DisabledPluginComponent
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  examples/templates/docker/air-gapped/image-building/README.md
Labels: kind/feature

#601 use RegistrationAddress for first controlPlane node if it is specified
  bootstrap/internal/controllers/rke2config_controller.go
Labels: kind/bug

#610 chore: Prepare main branch for v0.14 development
  docs/book/src/01_user/01_getting-started.md
  metadata.yaml
  test/e2e/config/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_upgrade_test.go
Labels: area/build-and-release
