Repository rancher/cluster-api-provider-rke2, pull requests merged in 2025-04, with the labels that each got.

#611 Adds RKE2ControlPlane labels to Machines
  controlplane/internal/controllers/scale.go
  test/e2e/data/infrastructure/cluster-template-docker-updated.yaml
  test/e2e/data/infrastructure/cluster-template-docker.yaml
  test/e2e/e2e_upgrade_test.go
  test/e2e/helpers.go
Labels: kind/bug

#612 Fix typos in the docs
  docs/book/src/01_user/01_getting-started.md
  docs/book/src/02_topics/01_air-gapped-installation.md
Labels: area/documentation

#619 Bump golangci-lint to v2
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  bootstrap/internal/cloudinit/cloudinit.go
  bootstrap/internal/cloudinit/controlplane_init.go
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/internal/ignition/ignition.go
  controlplane/api/v1beta1/groupversion_info.go
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/internal/controllers/scale.go
  hack/ensure-golangci-lint.sh
  pkg/rke2/config.go
  pkg/rke2/workload_cluster.go
  test/helpers/envtest.go
Labels: kind/cleanup, area/ci

#615 Add e2e test to prevent Machine rollout on provider upgrade
  test/e2e/e2e_upgrade_test.go
  test/e2e/helpers.go
Labels: area/controller, area/e2e-testing, kind/support

#621 🌱 Add openstack cluster template to examples
  examples/templates/openstack/cluster-template.yaml
Labels: kind/chore

#599 ⚠️ In-place propagation support for RKE2ControlPlane
  Makefile
  bootstrap/internal/ignition/ignition_test.go
  controlplane/api/v1alpha1/conversion.go
  controlplane/api/v1beta1/rke2controlplane_types.go
  controlplane/api/v1beta1/rke2controlplane_webhook.go
  controlplane/api/v1beta1/rke2controlplanetemplate_webhook.go
  controlplane/api/v1beta1/zz_generated.deepcopy.go
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanes.yaml
  controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_rke2controlplanetemplates.yaml
  controlplane/internal/contract/doc.go
  controlplane/internal/contract/types.go
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/internal/controllers/rke2controlplane_controller_test.go
  controlplane/internal/controllers/scale.go
  controlplane/internal/controllers/suite_test.go
  controlplane/internal/util/hash/hash.go
  controlplane/internal/util/ssa/cache.go
  controlplane/internal/util/ssa/filterintent.go
  controlplane/internal/util/ssa/managedfields.go
  controlplane/internal/util/ssa/patch.go
  docs/book/src/02_topics/02_node-registration-methods.md
  examples/clusterclass/docker/clusterclass-template.yaml
  examples/templates/aws/cluster-template-ignition.yaml
  examples/templates/aws/cluster-template.yaml
  examples/templates/docker/air-gapped/cluster-template.yaml
  examples/templates/docker/cluster-template-cis-profile.yaml
  examples/templates/docker/cluster-template-disable-components.yaml
  examples/templates/docker/cluster-template-kube-vip.yaml
  examples/templates/docker/cluster-template-multus-cni.yaml
  examples/templates/docker/cluster-template-private-registries.yaml
  examples/templates/docker/cluster-template.yaml
  examples/templates/docker/enable-multus/rke2controlplane-test.yaml
  examples/templates/vmware/cluster-template.yaml
  go.mod
  go.sum
  pkg/rke2/control_plane.go
  pkg/rke2/machine_filters.go
  pkg/rke2/workload_cluster.go
  pkg/rke2/workload_cluster_test.go
  test/e2e/data/infrastructure/cluster-template-docker-updated.yaml
  test/e2e/e2e_in_place_propagation_test.go
  test/e2e/e2e_upgrade_test.go
  test/e2e/helpers.go
Labels: area/api, kind/feature, squad/providers

#624 Enable concurrency in controllers
  bootstrap/internal/controllers/rke2config_controller.go
  bootstrap/main.go
  controlplane/internal/controllers/rke2controlplane_controller.go
  controlplane/main.go
Labels: kind/bug

#637 Allow using Gzip and GzipBase64 encoding in case of cloud-init format
  bootstrap/api/v1beta1/rke2config_webhook.go
Labels: area/bootstrap, kind/refactor

#631 🐛 Ignition: Don't add /opt fs on flatcar
  bootstrap/internal/ignition/butane/butane.go
  bootstrap/internal/ignition/butane/butane_test.go
Labels: area/bootstrap, kind/bug
